name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    run-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.jobs
        uses: actions/setup-node@v4
        with:
          node-version: 22.15

      - name: Instalar dependências
        run: npm i

      - name: Rodar os testes
        run: npm run test
